package entidades;
// Generated 24-may-2019 9:21:00 by Hibernate Tools 4.3.1



/**
 * Mascota generated by hbm2java
 */
public class Mascota  implements java.io.Serializable {


     private int idMascota;
     private String nombreMascota;
     private String mascotaCliente;
     private String raza;

    public Mascota() {
    }

    public Mascota(int idMascota, String nombreMascota, String mascotaCliente, String raza) {
       this.idMascota = idMascota;
       this.nombreMascota = nombreMascota;
       this.mascotaCliente = mascotaCliente;
       this.raza = raza;
    }
   
    public int getIdMascota() {
        return this.idMascota;
    }
    
    public void setIdMascota(int idMascota) {
        this.idMascota = idMascota;
    }
    public String getNombreMascota() {
        return this.nombreMascota;
    }
    
    public void setNombreMascota(String nombreMascota) {
        this.nombreMascota = nombreMascota;
    }
    public String getMascotaCliente() {
        return this.mascotaCliente;
    }
    
    public void setMascotaCliente(String mascotaCliente) {
        this.mascotaCliente = mascotaCliente;
    }
    public String getRaza() {
        return this.raza;
    }
    
    public void setRaza(String raza) {
        this.raza = raza;
    }




}


